/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.app.hrm.UI;

import com.app.hrm.DAO.ChucVuDao;
import com.app.hrm.DAO.NhanVienDao;
import com.app.hrm.DAO.PhongBanDao;
import com.app.hrm.DAO.PhuCapDao;
import com.app.hrm.DAO.TrinhDoDao;
import com.app.hrm.Entity.NhanVien;
import com.app.hrm.Entity.PhuCap;
import com.app.hrm.Utils.XImage;
import java.awt.Component;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class test3 extends javax.swing.JFrame {
     NhanVienDao dao = new NhanVienDao();
    PhongBanDao pbdao = new PhongBanDao();
    TrinhDoDao tddao = new TrinhDoDao();
    ChucVuDao cvdao = new ChucVuDao();
    /**
     * Creates new form test3
     */
    public test3() {
        initComponents();
        filltable();
    }
    
    void filltable(){
        DefaultTableModel tblMode = (DefaultTableModel) tbltest.getModel();
        tblMode.setRowCount(0);
        
        try {
            
            List<NhanVien> list = dao.selectByKey("");
            for (NhanVien nv : list) {
                String trinhDo = tddao.selectById(nv.getIDTD()).getTrinhDo();
                String chucVu = cvdao.selectById(nv.getIDCV()).getTenCV();
                String phongban = pbdao.selectById(nv.getIDPB()).getTenPhongban();
                
                
         
                Object[] row = {nv.getMaNV(), nv.getHoTen(),nv.getHinh() };
                tblMode.addRow(row);
            }
          
        tbltest.getColumnModel().getColumn(2).setCellRenderer(new ImageRender());
     
       tbltest.setRowHeight(40);
    
      
        } catch (Exception e) {
            e.printStackTrace();
        }  
    }
    
    private class ImageRender extends DefaultTableCellRenderer{

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            if(value != null){
                try {
                    String photo = value.toString();
                    File path = new File("src\\main\\resources\\com\\app\\hrm\\logo",photo);
                    BufferedImage image = ImageIO.read(path);
                    ImageIcon icon = new ImageIcon(image.getScaledInstance(35,40 , Image.SCALE_SMOOTH));
                    return new  JLabel(icon);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
            return new  JLabel("Không có hình");
            
        }
             
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbltest = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbltest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ma", "ten", "hinh"
            }
        ));
        tbltest.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbltest.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tbltest);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbltest;
    // End of variables declaration//GEN-END:variables
}
